"""Forçando nova migração

Revision ID: 14be2cf8ebd7
Revises: 7289e37b52b7
Create Date: 2025-03-26 15:08:12.184174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14be2cf8ebd7'
down_revision = '7289e37b52b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
