"""Criando tabela de periféricos

Revision ID: 5be017200dd1
Revises: eb4c1f1e7bb9
Create Date: 2025-03-26 22:49:52.717937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be017200dd1'
down_revision = 'eb4c1f1e7bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periferico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_entrada', sa.Date(), nullable=False))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periferico', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('data_entrada')

    # ### end Alembic commands ###
