"""Forçando nova migração

Revision ID: 60fd277d01be
Revises: 14be2cf8ebd7
Create Date: 2025-03-26 15:19:51.564291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60fd277d01be'
down_revision = '14be2cf8ebd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.alter_column('data_expiracao',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.alter_column('data_expiracao',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
