"""Forçando nova migração

Revision ID: 7289e37b52b7
Revises: 
Create Date: 2025-03-26 14:29:50.325204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7289e37b52b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_entrada', sa.Date(), nullable=True))
        batch_op.drop_column('data_aquisicao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_aquisicao', sa.DATE(), nullable=True))
        batch_op.drop_column('data_entrada')

    # ### end Alembic commands ###
