"""Novas colunas no hardware

Revision ID: 92c9435b277e
Revises: 5be017200dd1
Create Date: 2025-03-27 09:00:31.259709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c9435b277e'
down_revision = '5be017200dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processador', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('armazenamento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('memoria', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.drop_column('memoria')
        batch_op.drop_column('armazenamento')
        batch_op.drop_column('processador')

    # ### end Alembic commands ###
