"""Adicionando nova coluna 'descricao' à tabela hardware

Revision ID: 9f98785aa3f3
Revises: 92c9435b277e
Create Date: 2025-03-28 10:28:17.545211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f98785aa3f3'
down_revision = '92c9435b277e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('centro_dados')
    op.drop_table('historico_manutencao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_manutencao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('hardware_id', sa.INTEGER(), nullable=True),
    sa.Column('centro_dados_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['centro_dados_id'], ['centro_dados.id'], ),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('centro_dados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('localizacao', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('capacidade', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
