"""Adicionando novos campos ao modelo Hardware

Revision ID: eb4c1f1e7bb9
Revises: 60fd277d01be
Create Date: 2025-03-26 17:12:06.339310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4c1f1e7bb9'
down_revision = '60fd277d01be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setor', sa.String(length=50), nullable=True))

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.alter_column('data_expiracao',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.alter_column('data_expiracao',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.drop_column('setor')

    # ### end Alembic commands ###
